### ISSUE TITLE
Any example of getting the item data you pass into the component?

### ISSUE THREAD

**Issue by mekhami** [duiker101/poekit-rack#3]
I see your test_data.json stuff, but where do you get that information from? Do you have to do anything to format it?

**Comment by duiker101** [comment]
It come from the pathofexile website API. If you go to your character screen it will call a url like:

https://www.pathofexile.com/character-window/get-items?accountName=Duiker101&character=RuikerRF

**Comment by mekhami** [comment]
Okay thanks. I've forked this because I want to add the mods as the path of building style ranges rather than pulling the data from the stash. I've also ported it from Vue CLI 2 to 3, got rid of the pug, and put it in Standard js styleguide. This isn't to knock what you've done, just for reference and in case anyone else is interested. Thanks!
